name: flutter_donaciones_1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
 sdk: ^3.8.1

dependencies:
 cached_network_image: ^3.4.1
 dartz: ^0.10.1
 dio: ^5.4.1
 equatable: ^2.0.7
 flutter:
  sdk: flutter
 flutter_riverpod: ^2.6.1
 freezed_annotation: ^3.0.0
 gal: ^2.3.1
 geolocator: ^14.0.1
 get_it: ^8.0.3
 google_maps_flutter: ^2.12.2
 http: ^1.4.0
 image_picker: ^1.1.2
 intl: ^0.20.2
 json_annotation: ^4.9.0
 open_file: ^3.5.10
 path_provider: ^2.1.5
 permission_handler: ^12.0.0+1
 pretty_qr_code: ^3.4.0
 qr_flutter: ^4.1.0
 riverpod_annotation: ^2.6.1
 riverpod_generator: ^2.6.5
 shared_preferences: ^2.5.3
 url_launcher: ^6.3.2

dev_dependencies:
 build_runner: ^2.5.2
 flutter_lints: ^5.0.0
 flutter_test:
  sdk: flutter
 freezed: ^3.0.6
 json_serializable: ^6.9.5

flutter:
 uses-material-design: true
 assets:
  - assets/images/
